# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/2.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 380, 101, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-image: url(:/newPrefix/1.png);")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(40, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: rgb(0, 255, 127);\n"
"\n"
"")
        self.radioButton.setShortcut("")
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setShortcut("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 170, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color: rgb(0, 255, 127);")
        self.radioButton_3.setShortcut("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(230, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setShortcut("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(230, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setShortcut("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(230, 170, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setShortcut("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(420, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setShortcut("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(420, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setShortcut("")
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup.addButton(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(420, 170, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setShortcut("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup.addButton(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(610, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setShortcut("")
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup.addButton(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_11.setGeometry(QtCore.QRect(610, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setShortcut("")
        self.radioButton_11.setObjectName("radioButton_11")
        self.buttonGroup.addButton(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_12.setGeometry(QtCore.QRect(610, 170, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setShortcut("")
        self.radioButton_12.setObjectName("radioButton_12")
        self.buttonGroup.addButton(self.radioButton_12)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(190, 230, 401, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 380, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.start_swap)
        self.radioButton.clicked.connect(MainWindow.second_eight)
        self.radioButton_2.clicked.connect(MainWindow.second_ten)
        self.radioButton_3.clicked.connect(MainWindow.second_sixteen)
        self.radioButton_4.clicked.connect(MainWindow.eight_two)
        self.radioButton_5.clicked.connect(MainWindow.eight_ten)
        self.radioButton_6.clicked.connect(MainWindow.eigh_sixteen)
        self.radioButton_7.clicked.connect(MainWindow.ten_two)
        self.radioButton_8.clicked.connect(MainWindow.ten_eight)
        self.radioButton_9.clicked.connect(MainWindow.ten_sixteen)
        self.radioButton_10.clicked.connect(MainWindow.sixteen_two)
        self.radioButton_11.clicked.connect(MainWindow.sixteen_eight)
        self.radioButton_12.clicked.connect(MainWindow.sixteen_ten)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "进制转换"))
        self.pushButton.setText(_translate("MainWindow", "开始转换"))
        self.radioButton.setText(_translate("MainWindow", "二进制转八进制"))
        self.radioButton_2.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_2.setText(_translate("MainWindow", "二进制转十进制"))
        self.radioButton_3.setText(_translate("MainWindow", "二进制转十六进制"))
        self.radioButton_4.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_4.setText(_translate("MainWindow", "八进制转二进制"))
        self.radioButton_5.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_5.setText(_translate("MainWindow", "八进制转十进制"))
        self.radioButton_6.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_6.setText(_translate("MainWindow", "八进制转十六进制"))
        self.radioButton_7.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_7.setText(_translate("MainWindow", "十进制转二进制"))
        self.radioButton_8.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_8.setText(_translate("MainWindow", "十进制转八进制"))
        self.radioButton_9.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_9.setText(_translate("MainWindow", "十进制转十六进制"))
        self.radioButton_10.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_10.setText(_translate("MainWindow", "十六进制转二进制"))
        self.radioButton_11.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_11.setText(_translate("MainWindow", "十六进制转八进制"))
        self.radioButton_12.setStyleSheet(_translate("MainWindow", "color: rgb(0, 255, 127);"))
        self.radioButton_12.setText(_translate("MainWindow", "十六进制转十进制"))
